# Generated by Django 5.0.1 on 2025-03-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('buyer', 'Buyer'), ('administrator', 'Administrator')], default='buyer', max_length=15),
        ),
    ]
