# Generated by Django 5.0.1 on 2025-03-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_full_name_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
    ]
